name: Build and deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    # Build job
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [16.x, 18.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        # set default shell to bash
        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
              
            # Use cached dependencies if present, else cache dependencies if not present
            - name: Caching dependencies
              id: cache-node_modules
              uses: actions/cache@v3.3.1
              with:
                # A list of files, directories, and wildcard patterns to cache and restore
                path: ./node_modules
                # An explicit key for restoring and saving the cache
                key: node_modules-cache--${{ hashfiles('package-lock.json') }}
                # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
                enableCrossOsArchive: true

            - name: Install dependencies
              if: steps.cache-node_modules.outputs.cache-hit != true
              run: npm install
              
            # Compile build files and push the commit to the 'gh-pages' branch of the repo
            - name: Build files and commit to branch 'gh-pages' of repo
              run: |
                  npm run build
                  echo 'Checking out gh-pages branch'
                  git fetch --prune
                  git config user.email 'clive.dcosta98@gmail.com'
                  git config user.name 'clivedc'
                  git add .
                  git commit -m 'Compiled new build files'
                  git checkout -t origin/gh-pages
                  echo 'Cleaning gh-pages branch'
                  rm -rf *
                  echo 'Copying build files from main branch'
                  git checkout main -- build
                  echo 'Moving all files in build directory to root directory, ${{ github.workspace }}'
                  git mv build/* ./
                  echo 'Removing empty build folder'
                  rmdir build
                  echo 'Listing all files in current directory, ${{ github.workspace }}'
                  ls
                  echo 'Commit and push the changes to the gh-pages branch in the repo'
                  git add .
                  git commit -m "Compiled new build files"
                  git push origin gh-pages

    
    # Upload Build files
    build-and-upload-artifact:
        needs: build
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@v3
                with:
                    ref: gh-pages
              - name: Upload a Build Artifact
                uses: actions/upload-pages-artifact@v1
                with:
                    path: ./ 

    # Deploy job
    deploy:
        needs: build

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
