name: Build and deploy

on:
    push:
        branches: ["main"]
    pull_request:
        types: [closed]
        branches: ["main"]
    workflow_dispatch:

jobs:
    # Build job
    build:
        if: github.event_name == 'push' || github.event.pull_request.merged == true
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [16.x, 18.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        # set default shell to bash
        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: npm install and build
              run: |
                  npm install
                  npm run build
          
            
            - name: checkout gh-pages branch and copy build files
              run: |
                  echo ${{ github.workspace }}
                  git branch
                  git checkout -b gh-pages
                  git branch
                  rm -rf *
                  git checkout main -- build
                  git mv build/* ./
                  rmdir build
             
    # Build and upload artifact
    build-artifact:
       needs: build
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v3
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.2
          with:
            # Artifact name
            name: github-pages
            # A file, directory or wildcard pattern that describes what to upload
            path: ./
            # The desired behavior if no files are found using the provided path.
            # Available Options:
             # warn: Output a warning but do not fail the action
             # error: Fail the action with an error message
             # ignore: Do not output any warnings or errors, the action does not fail
            # optional, default is warn
            if-no-files-found: error

    # Deploy job
    deploy:
        needs: build-artifact

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1.2.5
